#!/usr/bin/env bash
# 1. Install your load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
ADJUSTMENT="
frontend 54.163.17.226
    bind 0:80
    default_backend backend_cluster
backend backend_cluster
    balance roundrobin
    server web-1 34.74.85.117:80
    server web-2 52.90.223.70:80"
echo "$ADJUSTMENT" >> /etc/haproxy/haproxy.cfg
sudo /etc/init.d/haproxy restart
