#!/usr/bin/env bash
# Install  nginx
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" > ~/index.html
sudo cp ~/index.html /var/www/html/index.html
sed -i "/server_name _;/a\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/\
sites-available/default
service nginx start
