#!/usr/bin/env bash
#  Listening on all active IPs on port 8080
sudo pkill apache2
file="/etc/nginx/sites-available/default"
sudo sed -i 's/ 80 / 8080 /g' "$file"
sudo sed -i 's/:80 / 8080 /g' "$file"
sudo sed -i 's/server_name localhost/server_name _/g' "$file"
sudo chmod 777 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
