#!/usr/bin/env bash
#  Listening on all active IPs on port 8080
sudo pkill apache2
file="/etc/nginx/sites-available/default"
sudo sed -i 's/ 80 / 8080 /g' "$file"
sudo sed -i 's/:80 / 8080 /g' "$file"
sudo sed -i 's/server_name localhost/server_name _/g' "$file"
sudo chown -R nginx:nginx /etc/nginx
sudo chmod -R 755 /etc/nginx/nginx.conf
sudo chsh -s /bin/bash nginx
sudo su -c "service nginx restart" nginx
