#!/usr/bin/env bash
#  Listening on all active IPs on port 8080
pkill -f apache2
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
