#!/usr/bin/env bash
# Based on Task 1
sudo pkill apache2
file="/etc/nginx/sites-available/default"
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' "$file"
sudo -u nginx service nginx start
